apiVersion: batch/v1
kind: Job
metadata:
  name: biocam-converter
spec:
  template:
    spec:
      containers:
      - name: biocam-converter
        image: aidanmorson/biocam_converter:latest
        volumeMounts:
        - name: biocam-data
          mountPath: /data
        args: ["/data/another_input_file.bxr", "/data/another_output_file.nwb"]
        resources:
          requests:
            memory: "512Mi"  # Request 512 MiB of memory
            cpu: "1"       # Request 1 CPU
            
          limits:
            memory: "614Mi"  # Limit to 614 MiB of memory
            cpu: "1.2"       # Limit to 1.2 CPUs
      volumes:
      - name: biocam-data
        persistentVolumeClaim:
          claimName: your-pvc-name
      restartPolicy: Never
  backoffLimit: 4
