apiVersion: batch/v1
kind: Job
metadata:
  name: curation-11-07-smitsmidbrain-all
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: curation
        image: aidanmorson/curation:v2
        imagePullPolicy: Always
        resources:

          # GPU Run
          requests:
            cpu: "4"
            memory: "75Gi"
            ephemeral-storage: "400Gi"
          limits:
            cpu: "4"
            memory: "75Gi"
            ephemeral-storage: "400Gi"

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "python", "si_curation.py"]
        args:
          - s3://braingeneers/ephys/2024-11-07-e-SmitsMidbrain-24hour/
          - s3://braingeneers/ephys/2024-11-07-e-SmitsMidbrain-24hour/params_midbrain_maxwell.json
        env:
          - name: "PYTHONUNBUFFERED"
            value: "true"
          # Ceph (internal)
          - name: "ENDPOINT_URL"
            value: "https://s3.braingeneers.gi.ucsc.edu"  # ceph internal
          - name: "S3_ENDPOINT"
            value: "s3.braingeneers.gi.ucsc.edu" # ceph internal

        volumeMounts:

          # Ceph credentials
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}