apiVersion: batch/v1
kind: Job
metadata:
  name: biocam-converter2
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: biocam-converter
        image: aidanmorson/biocam_converter:latest
        imagePullPolicy: Always
        resources:

          # GPU Run
          requests:
            cpu: "4"
            memory: "200Gi"
            ephemeral-storage: "250Gi"
          limits:
            cpu: "4"
            memory: "200Gi"
            ephemeral-storage: "250Gi"

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "python", "convert_brw_nwb.py"]
        args:
          - s3://braingeneers/ephys/2024-10-29-e-3Brain_SmitsMidbrain/original/data/10-29-24_SmitsMidbrainD46_GABAzine_01.brw
          - s3://braingeneers/ephys/2024-10-29-e-3Brain_SmitsMidbrain/shared/10-29-24_SmitsMidbrainD46_GABAzine_01.nwb
        env:
          - name: "PYTHONUNBUFFERED"
            value: "true"

          # Ceph (internal)
          - name: "ENDPOINT_URL"
            value: "https://s3.braingeneers.gi.ucsc.edu"  # ceph internal
          - name: "S3_ENDPOINT"
            value: "s3.braingeneers.gi.ucsc.edu" # ceph internal

        volumeMounts:

          # Ceph credentials
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"

      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}